//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceApi.MobiPhoneSmsService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thread.core.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://thread.core.com/", ConfigurationName="MobiPhoneSmsService.ReceiverProcess")]
    public interface ReceiverProcess {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://thread.core.com/ReceiverProcess/DeductionRequest", ReplyAction="http://thread.core.com/ReceiverProcess/DeductionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InvoiceApi.MobiPhoneSmsService.Exception), Action="http://thread.core.com/ReceiverProcess/Deduction/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvoiceApi.MobiPhoneSmsService.DeductionResponse Deduction(InvoiceApi.MobiPhoneSmsService.DeductionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thread.core.com/ReceiverProcess/DeductionRequest", ReplyAction="http://thread.core.com/ReceiverProcess/DeductionResponse")]
        System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.DeductionResponse> DeductionAsync(InvoiceApi.MobiPhoneSmsService.DeductionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://thread.core.com/ReceiverProcess/DepositRequest", ReplyAction="http://thread.core.com/ReceiverProcess/DepositResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InvoiceApi.MobiPhoneSmsService.Exception), Action="http://thread.core.com/ReceiverProcess/Deposit/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvoiceApi.MobiPhoneSmsService.DepositResponse Deposit(InvoiceApi.MobiPhoneSmsService.DepositRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thread.core.com/ReceiverProcess/DepositRequest", ReplyAction="http://thread.core.com/ReceiverProcess/DepositResponse")]
        System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.DepositResponse> DepositAsync(InvoiceApi.MobiPhoneSmsService.DepositRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://thread.core.com/ReceiverProcess/CheckamountRequest", ReplyAction="http://thread.core.com/ReceiverProcess/CheckamountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InvoiceApi.MobiPhoneSmsService.Exception), Action="http://thread.core.com/ReceiverProcess/Checkamount/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvoiceApi.MobiPhoneSmsService.CheckamountResponse Checkamount(InvoiceApi.MobiPhoneSmsService.CheckamountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thread.core.com/ReceiverProcess/CheckamountRequest", ReplyAction="http://thread.core.com/ReceiverProcess/CheckamountResponse")]
        System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.CheckamountResponse> CheckamountAsync(InvoiceApi.MobiPhoneSmsService.CheckamountRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://thread.core.com/ReceiverProcess/sendRequest", ReplyAction="http://thread.core.com/ReceiverProcess/sendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InvoiceApi.MobiPhoneSmsService.Exception), Action="http://thread.core.com/ReceiverProcess/send/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvoiceApi.MobiPhoneSmsService.sendResponse send(InvoiceApi.MobiPhoneSmsService.sendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thread.core.com/ReceiverProcess/sendRequest", ReplyAction="http://thread.core.com/ReceiverProcess/sendResponse")]
        System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.sendResponse> sendAsync(InvoiceApi.MobiPhoneSmsService.sendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Deduction", WrapperNamespace="http://thread.core.com/", IsWrapped=true)]
    public partial class DeductionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AMOUNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTP;
        
        public DeductionRequest() {
        }
        
        public DeductionRequest(string USERNAME, string PASSWORD, string AMOUNT, string OTP) {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.AMOUNT = AMOUNT;
            this.OTP = OTP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeductionResponse", WrapperNamespace="http://thread.core.com/", IsWrapped=true)]
    public partial class DeductionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public DeductionResponse() {
        }
        
        public DeductionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Deposit", WrapperNamespace="http://thread.core.com/", IsWrapped=true)]
    public partial class DepositRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AMOUNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTP;
        
        public DepositRequest() {
        }
        
        public DepositRequest(string USERNAME, string PASSWORD, string AMOUNT, string OTP) {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.AMOUNT = AMOUNT;
            this.OTP = OTP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DepositResponse", WrapperNamespace="http://thread.core.com/", IsWrapped=true)]
    public partial class DepositResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public DepositResponse() {
        }
        
        public DepositResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Checkamount", WrapperNamespace="http://thread.core.com/", IsWrapped=true)]
    public partial class CheckamountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        public CheckamountRequest() {
        }
        
        public CheckamountRequest(string USERNAME, string PASSWORD) {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckamountResponse", WrapperNamespace="http://thread.core.com/", IsWrapped=true)]
    public partial class CheckamountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CheckamountResponse() {
        }
        
        public CheckamountResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://thread.core.com/", IsWrapped=true)]
    public partial class sendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTENT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPERATOR_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAMPAIGN_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        public sendRequest() {
        }
        
        public sendRequest(string ISDN, string BRANDNAME, string CONTENT, string OPERATOR_ID, string CAMPAIGN_CODE, string TYPE, string USERNAME, string PASSWORD) {
            this.ISDN = ISDN;
            this.BRANDNAME = BRANDNAME;
            this.CONTENT = CONTENT;
            this.OPERATOR_ID = OPERATOR_ID;
            this.CAMPAIGN_CODE = CAMPAIGN_CODE;
            this.TYPE = TYPE;
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="http://thread.core.com/", IsWrapped=true)]
    public partial class sendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thread.core.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendResponse() {
        }
        
        public sendResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceiverProcessChannel : InvoiceApi.MobiPhoneSmsService.ReceiverProcess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiverProcessClient : System.ServiceModel.ClientBase<InvoiceApi.MobiPhoneSmsService.ReceiverProcess>, InvoiceApi.MobiPhoneSmsService.ReceiverProcess {
        
        public ReceiverProcessClient() {
        }
        
        public ReceiverProcessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiverProcessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiverProcessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiverProcessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvoiceApi.MobiPhoneSmsService.DeductionResponse InvoiceApi.MobiPhoneSmsService.ReceiverProcess.Deduction(InvoiceApi.MobiPhoneSmsService.DeductionRequest request) {
            return base.Channel.Deduction(request);
        }
        
        public string Deduction(string USERNAME, string PASSWORD, string AMOUNT, string OTP) {
            InvoiceApi.MobiPhoneSmsService.DeductionRequest inValue = new InvoiceApi.MobiPhoneSmsService.DeductionRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.AMOUNT = AMOUNT;
            inValue.OTP = OTP;
            InvoiceApi.MobiPhoneSmsService.DeductionResponse retVal = ((InvoiceApi.MobiPhoneSmsService.ReceiverProcess)(this)).Deduction(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.DeductionResponse> InvoiceApi.MobiPhoneSmsService.ReceiverProcess.DeductionAsync(InvoiceApi.MobiPhoneSmsService.DeductionRequest request) {
            return base.Channel.DeductionAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.DeductionResponse> DeductionAsync(string USERNAME, string PASSWORD, string AMOUNT, string OTP) {
            InvoiceApi.MobiPhoneSmsService.DeductionRequest inValue = new InvoiceApi.MobiPhoneSmsService.DeductionRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.AMOUNT = AMOUNT;
            inValue.OTP = OTP;
            return ((InvoiceApi.MobiPhoneSmsService.ReceiverProcess)(this)).DeductionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvoiceApi.MobiPhoneSmsService.DepositResponse InvoiceApi.MobiPhoneSmsService.ReceiverProcess.Deposit(InvoiceApi.MobiPhoneSmsService.DepositRequest request) {
            return base.Channel.Deposit(request);
        }
        
        public string Deposit(string USERNAME, string PASSWORD, string AMOUNT, string OTP) {
            InvoiceApi.MobiPhoneSmsService.DepositRequest inValue = new InvoiceApi.MobiPhoneSmsService.DepositRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.AMOUNT = AMOUNT;
            inValue.OTP = OTP;
            InvoiceApi.MobiPhoneSmsService.DepositResponse retVal = ((InvoiceApi.MobiPhoneSmsService.ReceiverProcess)(this)).Deposit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.DepositResponse> InvoiceApi.MobiPhoneSmsService.ReceiverProcess.DepositAsync(InvoiceApi.MobiPhoneSmsService.DepositRequest request) {
            return base.Channel.DepositAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.DepositResponse> DepositAsync(string USERNAME, string PASSWORD, string AMOUNT, string OTP) {
            InvoiceApi.MobiPhoneSmsService.DepositRequest inValue = new InvoiceApi.MobiPhoneSmsService.DepositRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.AMOUNT = AMOUNT;
            inValue.OTP = OTP;
            return ((InvoiceApi.MobiPhoneSmsService.ReceiverProcess)(this)).DepositAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvoiceApi.MobiPhoneSmsService.CheckamountResponse InvoiceApi.MobiPhoneSmsService.ReceiverProcess.Checkamount(InvoiceApi.MobiPhoneSmsService.CheckamountRequest request) {
            return base.Channel.Checkamount(request);
        }
        
        public string Checkamount(string USERNAME, string PASSWORD) {
            InvoiceApi.MobiPhoneSmsService.CheckamountRequest inValue = new InvoiceApi.MobiPhoneSmsService.CheckamountRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            InvoiceApi.MobiPhoneSmsService.CheckamountResponse retVal = ((InvoiceApi.MobiPhoneSmsService.ReceiverProcess)(this)).Checkamount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.CheckamountResponse> InvoiceApi.MobiPhoneSmsService.ReceiverProcess.CheckamountAsync(InvoiceApi.MobiPhoneSmsService.CheckamountRequest request) {
            return base.Channel.CheckamountAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.CheckamountResponse> CheckamountAsync(string USERNAME, string PASSWORD) {
            InvoiceApi.MobiPhoneSmsService.CheckamountRequest inValue = new InvoiceApi.MobiPhoneSmsService.CheckamountRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            return ((InvoiceApi.MobiPhoneSmsService.ReceiverProcess)(this)).CheckamountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvoiceApi.MobiPhoneSmsService.sendResponse InvoiceApi.MobiPhoneSmsService.ReceiverProcess.send(InvoiceApi.MobiPhoneSmsService.sendRequest request) {
            return base.Channel.send(request);
        }
        
        public string send(string ISDN, string BRANDNAME, string CONTENT, string OPERATOR_ID, string CAMPAIGN_CODE, string TYPE, string USERNAME, string PASSWORD) {
            InvoiceApi.MobiPhoneSmsService.sendRequest inValue = new InvoiceApi.MobiPhoneSmsService.sendRequest();
            inValue.ISDN = ISDN;
            inValue.BRANDNAME = BRANDNAME;
            inValue.CONTENT = CONTENT;
            inValue.OPERATOR_ID = OPERATOR_ID;
            inValue.CAMPAIGN_CODE = CAMPAIGN_CODE;
            inValue.TYPE = TYPE;
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            InvoiceApi.MobiPhoneSmsService.sendResponse retVal = ((InvoiceApi.MobiPhoneSmsService.ReceiverProcess)(this)).send(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.sendResponse> InvoiceApi.MobiPhoneSmsService.ReceiverProcess.sendAsync(InvoiceApi.MobiPhoneSmsService.sendRequest request) {
            return base.Channel.sendAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceApi.MobiPhoneSmsService.sendResponse> sendAsync(string ISDN, string BRANDNAME, string CONTENT, string OPERATOR_ID, string CAMPAIGN_CODE, string TYPE, string USERNAME, string PASSWORD) {
            InvoiceApi.MobiPhoneSmsService.sendRequest inValue = new InvoiceApi.MobiPhoneSmsService.sendRequest();
            inValue.ISDN = ISDN;
            inValue.BRANDNAME = BRANDNAME;
            inValue.CONTENT = CONTENT;
            inValue.OPERATOR_ID = OPERATOR_ID;
            inValue.CAMPAIGN_CODE = CAMPAIGN_CODE;
            inValue.TYPE = TYPE;
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            return ((InvoiceApi.MobiPhoneSmsService.ReceiverProcess)(this)).sendAsync(inValue);
        }
    }
}
